create table if not exists company_fact_metrics (
  id bigint generated by default as identity primary key,
  ticker text not null,
  cik text not null,
  company text not null,
  metric_key text not null,
  metric_label text not null,
  taxonomy text not null,
  unit text not null,
  fiscal_year integer,
  fiscal_period text,
  period_end date,
  filed_at date,
  form text,
  frame text,
  value_numeric numeric not null,
  source_document_key text not null,
  raw_fact_json jsonb not null default '{}',
  created_at timestamptz not null default now(),
  unique(ticker, metric_key, unit, period_end, fiscal_period, form)
);

create table if not exists stock_universe_memberships (
  id bigint generated by default as identity primary key,
  ticker text not null unique,
  cik text not null,
  company text not null,
  universe_name text not null,
  theme text not null,
  strategy_type text not null check(strategy_type in ('Conservative', 'Balanced', 'Aggressive')),
  source_key text not null,
  included_at timestamptz not null default now()
);

create table if not exists data_quality_checks (
  id bigint generated by default as identity primary key,
  run_key text not null,
  check_name text not null,
  target_table text not null,
  actual numeric not null,
  target numeric not null,
  status text not null check(status in ('pass', 'warn', 'fail')),
  insight text not null,
  created_at timestamptz not null default now(),
  unique(run_key, check_name, target_table)
);

create index if not exists company_fact_metrics_ticker_metric_idx
on company_fact_metrics(ticker, metric_key, period_end desc);

create index if not exists company_fact_metrics_metric_period_idx
on company_fact_metrics(metric_key, period_end desc);

create index if not exists stock_scores_stock_date_idx
on stock_scores(stock_id, score_date desc);

create index if not exists stock_recommendations_stock_created_idx
on stock_recommendations(stock_id, created_at desc);

create index if not exists data_quality_checks_run_status_idx
on data_quality_checks(run_key, status);
