create table if not exists stocks (
  id bigint generated by default as identity primary key,
  ticker text not null unique,
  company text not null,
  sector text not null,
  strategy_type text not null check(strategy_type in ('Conservative', 'Balanced', 'Aggressive')),
  rotation_theme text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists stock_scores (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references stocks(id),
  score_date date not null,
  final_score numeric not null,
  confidence_score numeric not null,
  factor_snapshot_json jsonb not null default '{}',
  model_version text not null,
  created_at timestamptz not null default now()
);

create table if not exists stock_recommendations (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references stocks(id),
  score_id bigint not null references stock_scores(id),
  expected_return text not null,
  expected_timeline text not null,
  risk_level text not null,
  why_picked text not null,
  key_catalyst text not null,
  key_risk text not null,
  disclaimer text not null,
  created_at timestamptz not null default now()
);

create table if not exists human_feedback (
  id bigint generated by default as identity primary key,
  recommendation_id bigint not null references stock_recommendations(id),
  user_decision text not null check(user_decision in ('approve', 'deny', 'escalate')),
  reviewer_note text,
  override_flag boolean not null default false,
  model_version text not null,
  feature_snapshot_json jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists user_investor_profiles (
  id bigint generated by default as identity primary key,
  user_id text not null,
  preferred_strategy text not null check(preferred_strategy in ('Conservative', 'Balanced', 'Aggressive')),
  inferred_risk_appetite text not null check(inferred_risk_appetite in ('Capital Protection', 'Balanced Growth', 'High Upside')),
  time_horizon text not null,
  drawdown_comfort text not null check(drawdown_comfort in ('Low', 'Medium', 'High')),
  experience_level text not null,
  onboarding_answers_json jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists portfolio_connections (
  id bigint generated by default as identity primary key,
  user_id text not null,
  provider text not null,
  connection_status text not null check(connection_status in ('pending', 'connected', 'disconnected', 'error')),
  holdings_snapshot_json jsonb not null default '{}',
  last_synced_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists personalized_recommendations (
  id bigint generated by default as identity primary key,
  user_id text not null,
  stock_id bigint not null references stocks(id),
  base_score numeric not null,
  personalized_score numeric not null,
  strategy_fit_score numeric not null,
  risk_fit_score numeric not null,
  portfolio_fit_score numeric not null,
  agent_rationale_json jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists learning_events (
  id bigint generated by default as identity primary key,
  user_id text not null,
  event_type text not null,
  ticker text,
  signal text not null,
  weight_adjustment numeric not null,
  model_version text not null,
  personalization_snapshot_json jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists evaluation_runs (
  id bigint generated by default as identity primary key,
  run_date date not null,
  benchmark text not null,
  portfolio_return numeric not null,
  benchmark_return numeric not null,
  win_rate numeric not null,
  max_drawdown numeric not null,
  retrieval_precision numeric,
  evidence_coverage numeric,
  actionable_insight text not null,
  created_at timestamptz not null default now()
);

create table if not exists model_updates (
  id bigint generated by default as identity primary key,
  model_version text not null,
  candidate_version text not null,
  training_signal text not null,
  validation_result text not null,
  approved_by text,
  deployed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists personalization_model_updates (
  id bigint generated by default as identity primary key,
  model_version text not null,
  candidate_version text not null,
  learning_event_count integer not null,
  global_ranking_change_json jsonb not null default '{}',
  personalization_change_json jsonb not null default '{}',
  validation_result text not null,
  approved_by text,
  deployed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists active_app_states (
  id bigint generated by default as identity primary key,
  user_id text not null,
  state_date date not null,
  schema_version text not null,
  model_version text not null,
  active_surface text not null check(active_surface in ('Discover', 'Decide', 'Connect', 'Menu')),
  profile_snapshot_json jsonb not null default '{}',
  discover_snapshot_json jsonb not null default '{}',
  decide_snapshot_json jsonb not null default '{}',
  connect_snapshot_json jsonb not null default '{}',
  learning_snapshot_json jsonb not null default '{}',
  evaluation_snapshot_json jsonb not null default '{}',
  disclaimer text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, state_date, schema_version)
);

create table if not exists market_synthesis_signals (
  id bigint generated by default as identity primary key,
  state_id bigint not null references active_app_states(id),
  signal_key text not null,
  category text not null,
  headline text not null,
  summary text not null,
  user_translation text not null,
  confidence numeric not null,
  source_type text not null,
  created_at timestamptz not null default now()
);

create table if not exists ranked_stock_options (
  id bigint generated by default as identity primary key,
  state_id bigint not null references active_app_states(id),
  ticker text not null,
  rank integer not null,
  theme text not null,
  fit_label text not null,
  reason text not null,
  action text not null,
  expected_return text not null,
  expected_timeline text not null,
  risk_level text not null,
  personalized_score numeric not null,
  created_at timestamptz not null default now()
);

create table if not exists broker_providers (
  id bigint generated by default as identity primary key,
  provider_key text not null unique,
  name text not null,
  connection_status text not null check(connection_status in ('available', 'connected', 'coming_soon')),
  auth_pattern text not null check(auth_pattern in ('oauth', 'aggregator', 'manual')),
  purpose text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists source_registry (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  name text not null,
  provider text not null,
  source_family text not null check(source_family in ('premium_news', 'open_filings', 'macro_data', 'market_data', 'fundamentals', 'portfolio')),
  access_model text not null check(access_model in ('licensed', 'api_key', 'public', 'sandbox')),
  cadence text not null check(cadence in ('30m', '60m', 'daily', 'event')),
  quality_tier text not null check(quality_tier in ('enterprise', 'official', 'commercial', 'prototype')),
  endpoint_pattern text not null,
  env_keys_json jsonb not null default '[]',
  facets_json jsonb not null default '[]',
  lineage_policy text not null,
  enabled_for_mvp boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists ingestion_runs (
  id bigint generated by default as identity primary key,
  run_key text not null unique,
  source_id bigint not null references source_registry(id),
  status text not null check(status in ('queued', 'running', 'completed', 'failed', 'skipped')),
  cadence text not null check(cadence in ('30m', '60m', 'daily', 'event')),
  started_at timestamptz not null,
  completed_at timestamptz,
  records_seen integer not null default 0,
  records_accepted integer not null default 0,
  records_rejected integer not null default 0,
  output_tables_json jsonb not null default '[]',
  notes text not null,
  created_at timestamptz not null default now()
);

create table if not exists raw_source_events (
  id bigint generated by default as identity primary key,
  ingestion_run_id bigint not null references ingestion_runs(id),
  source_id bigint not null references source_registry(id),
  provider_event_id text not null,
  event_type text not null,
  event_timestamp timestamptz not null,
  source_url text,
  raw_metadata_json jsonb not null default '{}',
  body_storage_policy text not null check(body_storage_policy in ('metadata_only', 'licensed_excerpt', 'full_text_allowed')),
  created_at timestamptz not null default now()
);

create table if not exists source_documents (
  id bigint generated by default as identity primary key,
  raw_event_id bigint not null references raw_source_events(id),
  document_key text not null,
  source_title text not null,
  source_author text,
  published_at timestamptz not null,
  canonical_url text,
  source_excerpt text,
  rights_status text not null check(rights_status in ('public', 'licensed_metadata_only', 'licensed_excerpt', 'licensed_full_text')),
  checksum text not null,
  created_at timestamptz not null default now()
);

create table if not exists extracted_market_signals (
  id bigint generated by default as identity primary key,
  source_document_id bigint not null references source_documents(id),
  signal_key text not null,
  signal_category text not null,
  signal_summary text not null,
  affected_tickers_json jsonb not null default '[]',
  affected_themes_json jsonb not null default '[]',
  scoring_factors_json jsonb not null default '[]',
  confidence numeric not null,
  extraction_model_version text not null,
  extracted_at timestamptz not null default now()
);

create table if not exists signal_trace_links (
  id bigint generated by default as identity primary key,
  signal_id bigint not null references extracted_market_signals(id),
  target_table text not null,
  target_record_key text not null,
  decision_surface text not null check(decision_surface in ('Discover', 'Decide', 'Connect', 'Menu')),
  transformation_step text not null,
  factor_delta_json jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists active_state_update_traces (
  id bigint generated by default as identity primary key,
  state_id bigint not null references active_app_states(id),
  ingestion_run_id bigint not null references ingestion_runs(id),
  update_reason text not null,
  source_signal_count integer not null,
  before_snapshot_json jsonb not null default '{}',
  after_snapshot_json jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create unique index if not exists raw_source_events_provider_event_id_idx
on raw_source_events(provider_event_id);

create unique index if not exists source_documents_document_key_idx
on source_documents(document_key);

create unique index if not exists extracted_market_signals_signal_key_idx
on extracted_market_signals(signal_key);

create index if not exists ingestion_runs_source_status_started_idx
on ingestion_runs(source_id, status, started_at desc);

create index if not exists raw_source_events_source_event_timestamp_idx
on raw_source_events(source_id, event_timestamp desc);

create index if not exists extracted_market_signals_category_confidence_idx
on extracted_market_signals(signal_category, confidence desc);

create index if not exists signal_trace_links_target_idx
on signal_trace_links(target_table, target_record_key);

select
  table_schema,
  table_name
from information_schema.tables
where table_schema = 'public'
  and table_type = 'BASE TABLE'
order by table_name;
