-- Stock Pick Check initial schema.
-- Source of truth currently mirrors data/schema.sql for fast Supabase setup.

CREATE TABLE stocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker TEXT NOT NULL UNIQUE,
  company TEXT NOT NULL,
  sector TEXT NOT NULL,
  strategy_type TEXT NOT NULL CHECK(strategy_type IN ('Conservative', 'Balanced', 'Aggressive')),
  rotation_theme TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE user_investor_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  preferred_strategy TEXT NOT NULL CHECK(preferred_strategy IN ('Conservative', 'Balanced', 'Aggressive')),
  inferred_risk_appetite TEXT NOT NULL CHECK(inferred_risk_appetite IN ('Capital Protection', 'Balanced Growth', 'High Upside')),
  time_horizon TEXT NOT NULL,
  drawdown_comfort TEXT NOT NULL CHECK(drawdown_comfort IN ('Low', 'Medium', 'High')),
  experience_level TEXT NOT NULL,
  onboarding_answers_json JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE portfolio_connections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  provider TEXT NOT NULL,
  connection_status TEXT NOT NULL CHECK(connection_status IN ('pending', 'connected', 'disconnected', 'error')),
  holdings_snapshot_json JSONB NOT NULL DEFAULT '{}',
  last_synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE personalized_recommendations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  stock_id BIGINT NOT NULL REFERENCES stocks(id),
  base_score NUMERIC NOT NULL,
  personalized_score NUMERIC NOT NULL,
  strategy_fit_score NUMERIC NOT NULL,
  risk_fit_score NUMERIC NOT NULL,
  portfolio_fit_score NUMERIC NOT NULL,
  agent_rationale_json JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE learning_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  event_type TEXT NOT NULL,
  ticker TEXT,
  signal TEXT NOT NULL,
  weight_adjustment NUMERIC NOT NULL,
  model_version TEXT NOT NULL,
  personalization_snapshot_json JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE evaluation_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_date DATE NOT NULL,
  benchmark TEXT NOT NULL,
  portfolio_return NUMERIC NOT NULL,
  benchmark_return NUMERIC NOT NULL,
  win_rate NUMERIC NOT NULL,
  max_drawdown NUMERIC NOT NULL,
  retrieval_precision NUMERIC,
  evidence_coverage NUMERIC,
  actionable_insight TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE personalization_model_updates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_version TEXT NOT NULL,
  candidate_version TEXT NOT NULL,
  learning_event_count INTEGER NOT NULL,
  global_ranking_change_json JSONB NOT NULL DEFAULT '{}',
  personalization_change_json JSONB NOT NULL DEFAULT '{}',
  validation_result TEXT NOT NULL,
  approved_by TEXT,
  deployed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE active_app_states (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  state_date DATE NOT NULL,
  schema_version TEXT NOT NULL,
  model_version TEXT NOT NULL,
  active_surface TEXT NOT NULL CHECK(active_surface IN ('Discover', 'Decide', 'Connect', 'Menu')),
  profile_snapshot_json JSONB NOT NULL DEFAULT '{}',
  discover_snapshot_json JSONB NOT NULL DEFAULT '{}',
  decide_snapshot_json JSONB NOT NULL DEFAULT '{}',
  connect_snapshot_json JSONB NOT NULL DEFAULT '{}',
  learning_snapshot_json JSONB NOT NULL DEFAULT '{}',
  evaluation_snapshot_json JSONB NOT NULL DEFAULT '{}',
  disclaimer TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(user_id, state_date, schema_version)
);

CREATE TABLE source_registry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  provider TEXT NOT NULL,
  source_family TEXT NOT NULL CHECK(source_family IN ('premium_news', 'open_filings', 'macro_data', 'market_data', 'fundamentals', 'portfolio')),
  access_model TEXT NOT NULL CHECK(access_model IN ('licensed', 'api_key', 'public', 'sandbox')),
  cadence TEXT NOT NULL CHECK(cadence IN ('30m', '60m', 'daily', 'event')),
  quality_tier TEXT NOT NULL CHECK(quality_tier IN ('enterprise', 'official', 'commercial', 'prototype')),
  endpoint_pattern TEXT NOT NULL,
  env_keys_json JSONB NOT NULL DEFAULT '[]',
  facets_json JSONB NOT NULL DEFAULT '[]',
  lineage_policy TEXT NOT NULL,
  enabled_for_mvp BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE ingestion_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_key TEXT NOT NULL UNIQUE,
  source_id BIGINT NOT NULL REFERENCES source_registry(id),
  status TEXT NOT NULL CHECK(status IN ('queued', 'running', 'completed', 'failed', 'skipped')),
  cadence TEXT NOT NULL CHECK(cadence IN ('30m', '60m', 'daily', 'event')),
  started_at TIMESTAMPTZ NOT NULL,
  completed_at TIMESTAMPTZ,
  records_seen INTEGER NOT NULL DEFAULT 0,
  records_accepted INTEGER NOT NULL DEFAULT 0,
  records_rejected INTEGER NOT NULL DEFAULT 0,
  output_tables_json JSONB NOT NULL DEFAULT '[]',
  notes TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE raw_source_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingestion_run_id BIGINT NOT NULL REFERENCES ingestion_runs(id),
  source_id BIGINT NOT NULL REFERENCES source_registry(id),
  provider_event_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  event_timestamp TIMESTAMPTZ NOT NULL,
  source_url TEXT,
  raw_metadata_json JSONB NOT NULL DEFAULT '{}',
  body_storage_policy TEXT NOT NULL CHECK(body_storage_policy IN ('metadata_only', 'licensed_excerpt', 'full_text_allowed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE source_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  raw_event_id BIGINT NOT NULL REFERENCES raw_source_events(id),
  document_key TEXT NOT NULL,
  source_title TEXT NOT NULL,
  source_author TEXT,
  published_at TIMESTAMPTZ NOT NULL,
  canonical_url TEXT,
  source_excerpt TEXT,
  rights_status TEXT NOT NULL CHECK(rights_status IN ('public', 'licensed_metadata_only', 'licensed_excerpt', 'licensed_full_text')),
  checksum TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE extracted_market_signals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_document_id BIGINT NOT NULL REFERENCES source_documents(id),
  signal_key TEXT NOT NULL,
  signal_category TEXT NOT NULL,
  signal_summary TEXT NOT NULL,
  affected_tickers_json JSONB NOT NULL DEFAULT '[]',
  affected_themes_json JSONB NOT NULL DEFAULT '[]',
  scoring_factors_json JSONB NOT NULL DEFAULT '[]',
  confidence NUMERIC NOT NULL,
  extraction_model_version TEXT NOT NULL,
  extracted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE signal_trace_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signal_id BIGINT NOT NULL REFERENCES extracted_market_signals(id),
  target_table TEXT NOT NULL,
  target_record_key TEXT NOT NULL,
  decision_surface TEXT NOT NULL CHECK(decision_surface IN ('Discover', 'Decide', 'Connect', 'Menu')),
  transformation_step TEXT NOT NULL,
  factor_delta_json JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE active_state_update_traces (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state_id BIGINT NOT NULL REFERENCES active_app_states(id),
  ingestion_run_id BIGINT NOT NULL REFERENCES ingestion_runs(id),
  update_reason TEXT NOT NULL,
  source_signal_count INTEGER NOT NULL,
  before_snapshot_json JSONB NOT NULL DEFAULT '{}',
  after_snapshot_json JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
