-- Stock Pick Check initial schema.
-- Source of truth currently mirrors data/schema.sql for fast Supabase setup.

CREATE TABLE stocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker TEXT NOT NULL UNIQUE,
  company TEXT NOT NULL,
  sector TEXT NOT NULL,
  strategy_type TEXT NOT NULL CHECK(strategy_type IN ('Conservative', 'Balanced', 'Aggressive')),
  rotation_theme TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE user_investor_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  preferred_strategy TEXT NOT NULL CHECK(preferred_strategy IN ('Conservative', 'Balanced', 'Aggressive')),
  inferred_risk_appetite TEXT NOT NULL CHECK(inferred_risk_appetite IN ('Capital Protection', 'Balanced Growth', 'High Upside')),
  time_horizon TEXT NOT NULL,
  drawdown_comfort TEXT NOT NULL CHECK(drawdown_comfort IN ('Low', 'Medium', 'High')),
  experience_level TEXT NOT NULL,
  onboarding_answers_json JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE portfolio_connections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  provider TEXT NOT NULL,
  connection_status TEXT NOT NULL CHECK(connection_status IN ('pending', 'connected', 'disconnected', 'error')),
  holdings_snapshot_json JSONB NOT NULL DEFAULT '{}',
  last_synced_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE personalized_recommendations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  stock_id BIGINT NOT NULL REFERENCES stocks(id),
  base_score NUMERIC NOT NULL,
  personalized_score NUMERIC NOT NULL,
  strategy_fit_score NUMERIC NOT NULL,
  risk_fit_score NUMERIC NOT NULL,
  portfolio_fit_score NUMERIC NOT NULL,
  agent_rationale_json JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE learning_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL,
  event_type TEXT NOT NULL,
  ticker TEXT,
  signal TEXT NOT NULL,
  weight_adjustment NUMERIC NOT NULL,
  model_version TEXT NOT NULL,
  personalization_snapshot_json JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE evaluation_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_date DATE NOT NULL,
  benchmark TEXT NOT NULL,
  portfolio_return NUMERIC NOT NULL,
  benchmark_return NUMERIC NOT NULL,
  win_rate NUMERIC NOT NULL,
  max_drawdown NUMERIC NOT NULL,
  retrieval_precision NUMERIC,
  evidence_coverage NUMERIC,
  actionable_insight TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE personalization_model_updates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_version TEXT NOT NULL,
  candidate_version TEXT NOT NULL,
  learning_event_count INTEGER NOT NULL,
  global_ranking_change_json JSONB NOT NULL DEFAULT '{}',
  personalization_change_json JSONB NOT NULL DEFAULT '{}',
  validation_result TEXT NOT NULL,
  approved_by TEXT,
  deployed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
